//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        public string TaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public string MaDG { get; set; }
        public string MaTT { get; set; }
        public short VaiTro { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual DOCGIA DOCGIA { get; set; }
        public virtual THUTHU THUTHU { get; set; }
    }
}
