//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public string Id { get; set; }
        public string Ten { get; set; }
        public Nullable<System.DateTime> NgayLapThe { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
