//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAMETERS
    {
        public int ID { get; set; }
        public Nullable<short> IDDocGia { get; set; }
        public Nullable<short> IDSach { get; set; }
        public Nullable<short> IDPhieuMuon { get; set; }
        public Nullable<short> IDPhieuTra { get; set; }
        public Nullable<short> IDMaTT { get; set; }
    }
}
