//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAMETER
    {
        public int STT { get; set; }
        public int IDDocGia { get; set; }
        public int IDSach { get; set; }
        public int IDPhMuon { get; set; }
        public int IDPhThu { get; set; }
        public int IDPhTra { get; set; }
        public int SoNgMuonTD { get; set; }
        public int TuoiTThieu { get; set; }
    }
}
