//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAMETERS
    {
        public int ID { get; set; }
        public short IDDocGia { get; set; }
        public short IDThuThu { get; set; }
        public short IDSach { get; set; }
        public short IDPhieuMuon { get; set; }
        public short IDPhieuTra { get; set; }
        public short IDMaTT { get; set; }
    }
}
