//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SETTING
    {
        public int ID { get; set; }
        public Nullable<int> TuoiToiTieuDocGia { get; set; }
        public Nullable<int> TuoiToiDaDocGia { get; set; }
        public Nullable<int> TuoiToiTieuThuThu { get; set; }
        public Nullable<int> TuoiToiDaThuThu { get; set; }
        public Nullable<int> ThoiHanThe { get; set; }
        public Nullable<int> SoNgayMuonToiDa { get; set; }
        public Nullable<int> SoTienNopTre { get; set; }
        public Nullable<int> SoSachMuonToiDa { get; set; }
        public Nullable<int> SoLuongTheLoaiToiDa { get; set; }
        public Nullable<int> ThoiGianNhapSach { get; set; }
    }
}
