//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SETTING
    {
        public string IDSetting { get; set; }
        public int TuoiToiThieu { get; set; }
        public int TuoiToiDa { get; set; }
        public int ThoiHanThe { get; set; }
        public int SoNgayMuonToiDa { get; set; }
        public int SoTienNopTre { get; set; }
        public int SoSachMuonToiDa { get; set; }
        public int SoLuongTheLoaiToiDa { get; set; }
        public int ThoiGianNhapSach { get; set; }
    }
}
