//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvvm_demo.Models
{
    using System;
    using System.Collections.Generic;
    
<<<<<<<< HEAD:mvvm_demo/mvvm_demo/mvvm_demo/Models/Employee.cs
    public partial class Employee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
========
    public partial class ACCOUNT
    {
        public string TaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public string MaDG { get; set; }
        public string MaTT { get; set; }
        public short VaiTro { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual DOCGIA DOCGIA { get; set; }
        public virtual THUTHU THUTHU { get; set; }
>>>>>>>> main:QuanLyThuVien/Model/ACCOUNT.cs
    }
}
